//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LTWindows
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultyLogin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacultyLogin()
        {
            this.ProfileImages = new HashSet<ProfileImage>();
        }
    
        public int FacultyID { get; set; }
        public string Password { get; set; }
        public string JobTitle { get; set; }
        public string FacultyName { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<System.DateTime> LastChangePass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileImage> ProfileImages { get; set; }
    }
}
