//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LTWindows
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public string StudentID { get; set; }
        public string ClassID { get; set; }
        public string SubjectID { get; set; }
        public Nullable<double> Mid_term_Grade { get; set; }
        public Nullable<double> Last_term_Grade { get; set; }
        public Nullable<double> FinalGrade { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
