//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LTWindows
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileImage
    {
        public int ImageID { get; set; }
        public byte[] ProfileImage1 { get; set; }
        public Nullable<int> FacultyID { get; set; }
    
        public virtual FacultyLogin FacultyLogin { get; set; }
    }
}
